name: dbtvault_greenplum_demo
profile: dbtvault_greenplum_demo
version: '1.0.0'
config-version: 2

vars:
  load_date: '1992-01-01'
  # tpch_size: 10 #1, 10, 100, 1000, 10000

models:
  dbtvault_greenplum_demo:
    raw_stage:
      materialized: table
      tags: ['raw']
    stage:
      materialized: view
      tags: ['stage']
      enabled: true

    raw_vault:
      tags: ['raw_vault']
      materialized: incremental
      hubs:
        tags:
          - 'hub'
      links:
        tags:
          - 'link'
      sats:
        tags:
          - 'satellite'
      t_links:
        tags:
          - 't_link'
      pit:
        tags:
          - 'pit'
      bridge:
        tags:
          - 'bridge'
seeds:
  name: as_of_date

macro-paths:
  - macros
model-paths:
  - models
test-paths:
  - tests
target-path: target    
seeds-paths:
  - models

clean-targets:
    - "target"
    - "dbt_packages"

